sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
env:
  global:
    - DOCKER_USERNAME="cpollmeier"
    - secure: d4e5gT96oWojdp2wFL9qenXhf3OZlrZWei9sFc1WQz2U757eOb5SbnDSP/qegTTk2a4TO/Ekr4693eq33wk2/Vq9eIhnrurLpu/7BOV6DThj+y3bA72z/OWXzdFpPMsFDRm5QS2Rv6YbR9fUlOQ9HH+yN1hdnLS4ow2+DUSyRwqAigH8psUOqhKG0Wg7HYQnRmhh3x1RziApFJdX/iJPJZzzJsvdcGkh8Vj0p3AiMXGV/sJOJhN6tur8yEkHwqVzhqbf2H1ROEkFUKWKjZgc1Bh8KDQUWkktr50j8f+TENmwW+1L8SkwMFIkUOaOfqKUicCWor4QZ9tK6uOTlJHgH60tE5Yie8ICYdWIfTvhht4df3vcVy11MCpH00u83NV1EqyYpUkvIuP5BpI3A/mNwH3qg/y9csV++IvbEHbkh2j2F6y+71y2uTdaVhDv1HPWyrOmee5vAZoBeqlfA+rAh57z7qMTxn+mcjxrKTFFWHzMjXo4noGQgooq5QBuoQ+O1ivqe2y8za+llVWkhsQDP9tYkcNmR19cD21tRk7BDu9nv/9IW/BRp1OuB4qVz07jmxeCleB3n0R6SJA2VoUx0rCBD4v9rqjw2uSHf++KdJcMFJwUEN7T+LVipa4FHPsJsz7R9utoRJY1YsQxYxuiU/0+NyB+nhAUE0p+ZdclQoQ=

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - |
    if [ "$TRAVIS_BRANCH" == "master" -o "$TRAVIS_TAG" != "" ]; then
      for container in containers/*; do
        TAG=""

        if [ "$TRAVIS_BRANCH" == "master" ]; then
          TAG="$container:latest"
        elif [ "$TRAVIS_TAG" != "" ]; then
          TAG="$container:$TRAVIS_TAG"
        fi

        docker build -t $TAG $container
      done
    fi

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" -o "$TRAVIS_TAG" != "" ]; then
      for container in containers/*; do
        TAG=""

        if [ "$TRAVIS_BRANCH" == "master" ]; then
          TAG="$container:latest"
        elif [ "$TRAVIS_TAG" != "" ]; then
          TAG="$container:$TRAVIS_TAG"
        fi

        docker tag $TAG $DOCKER_USERNAME/$TAG
        docker push $DOCKER_USERNAME/$TAG
      done
    fi
