sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
env:
  global:
    - DOCKER_USERNAME="cpollmeier"
    - secure: LQXDq4sVWPxElLLiRDfT9fEKjVHNfthsTtkBI3HcaEVRaLtND/6v72qxA1ak8f+gpHyocQzfGnUThsdzZ1J5vza8JS0byHlmEP9KDLUQqVymcMx4wt/AHzHXZGBlLO9rd66tA6/fGWHXdyuGXg4NEt2D1OjypSrXLP2kOvXWKz/ujuTsWu9xVlahl3NhvMglFqsYruplZZlpYeaxewUbxq+kT6IaMcD96Uuir3AXTf+O1FAC7/XULZdqDZNCEtPgw4eEMj20c5j3wf27CTOs0roB8zNaC5IqWFbqPcJsblJ7dqrGRYU7/6fQ8KdlK+sVEkGOkKNf3UvHy+I35SnxbWc+QU0yHLKGpv0LTLAKNNvzCdCGj64NBVuaFg2hWjZtxGLk2nfEZXId4YS+wZ4eWf+gDHRGbofjbN0ydGWtqhdBpLRRXakDNkdjlDOmlQt1qyK2muFsqsGjo8tsO6z7yseIgXMcofpZ0+gvobdbnCoaE7bPpohAHNfYN+gskaF4UjDtngxc6KejeKl3vHuvZZRSsEgUwtowLnlr4Fd3oYsuraUlwlP0Z4DLBjz8mpY9j21u4dJc5xHUg0fBpFJoBhBMqB8AQ3Lr0WJl0K2czeVQJGZLzcUfpNYM20SXyy/p0ANGHrbfRIdTGhfAbd7dBMaVojjcE4v0VKMN6HLqO/g=

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - |
    TAG=""

    if [ "$TRAVIS_BRANCH" == "master" ]; then
      TAG="$container:latest"
    elsif [ "$TRAVIS_TAG" != "" ]; then
      TAG="$container:$TRAVIS_TAG"
    fi

install:
  - |
    if [ "$TAG" != "" ]; then
      for container in containers/*; do
        docker build -t $TAG $container
       done
    fi

after_success:
  - |
    if [ "$TAG" != "" ]; then
      for container in containers/*; do
        docker tag $TAG $DOCKER_USERNAME/$TAG
        docker push $DOCKER_USERNAME/$TAG
       done
    fi
