sudo: true
dist: trusty
language: node_js
node_js:
  - "8"
env:
  global:
    - secure: LQXDq4sVWPxElLLiRDfT9fEKjVHNfthsTtkBI3HcaEVRaLtND/6v72qxA1ak8f+gpHyocQzfGnUThsdzZ1J5vza8JS0byHlmEP9KDLUQqVymcMx4wt/AHzHXZGBlLO9rd66tA6/fGWHXdyuGXg4NEt2D1OjypSrXLP2kOvXWKz/ujuTsWu9xVlahl3NhvMglFqsYruplZZlpYeaxewUbxq+kT6IaMcD96Uuir3AXTf+O1FAC7/XULZdqDZNCEtPgw4eEMj20c5j3wf27CTOs0roB8zNaC5IqWFbqPcJsblJ7dqrGRYU7/6fQ8KdlK+sVEkGOkKNf3UvHy+I35SnxbWc+QU0yHLKGpv0LTLAKNNvzCdCGj64NBVuaFg2hWjZtxGLk2nfEZXId4YS+wZ4eWf+gDHRGbofjbN0ydGWtqhdBpLRRXakDNkdjlDOmlQt1qyK2muFsqsGjo8tsO6z7yseIgXMcofpZ0+gvobdbnCoaE7bPpohAHNfYN+gskaF4UjDtngxc6KejeKl3vHuvZZRSsEgUwtowLnlr4Fd3oYsuraUlwlP0Z4DLBjz8mpY9j21u4dJc5xHUg0fBpFJoBhBMqB8AQ3Lr0WJl0K2czeVQJGZLzcUfpNYM20SXyy/p0ANGHrbfRIdTGhfAbd7dBMaVojjcE4v0VKMN6HLqO/g=
    - secure: BgrDO0i6KXfOVBNLXH6VBCXnkpuslXOGVn7gbFu+ECfH+53DCMkD6148OtGY3CvQ2NAre0AUiVB6qSz0PLa/R4g98nFfTXhaMtNMz9WBJIGcyCPoQltjQWiT/EstaCbUY3bBbtgHp+s+fRyBke5nsVFF39YM1r5Hu2/kPJbeR1zI0N+B95pUbZ9wme0nXpowgeyvdSjSr54rqyhjbsHglSDVJ6h6w4v8HGAh9p1LSFSt98dUdreFoA052x3/bfGLZ/v59jMdr+iHBkSN/pGeyPnG5x9N0IyhKKX4uQJSriEGaH+U28hCcuUNK/UFuZU8e/yzLe5EPFN3+gZeKqBQtVxNllYtqDLXtMdJgr+sn3wKuELor4dWW5gBGuynLhmOUeYZ81t7liHwrtD7FKJVVeRJb7Yq2XwaCNKUn4rDy/LMxV6P7XbGsQHfk3z2urowhRmB0TDHKqC0X4qMX8HVxNtMWJm3WSunbWaNO1O0K8z+9LV5KJ30EWTNTbRAjIbitPEVsIuFgsAFuLCtFTMe5obwsOKKCZgVX6KXqcZGRgyWSHOi64pZv1DX71X0QaUkmmRDvBm0gbkL0GJ4keL/EQPO+WssmQGdyrcqHxlUTdYz3U6M5pSR4sL014z0HvbtWaRBTrRMqDV7Ayz+YEVYpUr2g93NAg3AEqPCu3jBS5s=


before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - |
    TAG=""

    if [ "$TRAVIS_BRANCH" == "master" ]; then
      TAG="$container:latest"
    elsif [ "$TRAVIS_TAG" != "" ]; then
      TAG="$container:$TRAVIS_TAG"
    fi

install:
  - |
    if [ "$TAG" != "" ]; then
      for container in containers/*; do
        docker build -t $TAG $container
       done
    fi

after_success:
  - |
    if [ "$TAG" != "" ]; then
      for container in containers/*; do
        docker tag $TAG $DOCKER_USERNAME/$TAG
        docker push $DOCKER_USERNAME/$TAG
       done
    fi
