version: "2.2"

services:

  openldap:
    extends:
      file: docker-compose.base.yml
      service: openldap
    ports:
      - "389:389"
      - "636:636"

  mqtt-backend:
    container_name: mqtt-backend
    extends:
      file: docker-compose.base.yml
      service: mqtt
    environment:
      HTTP_AUTH_HOST: ${HTTP_AUTH_HOST}
    ports:
      - "1883:1883"

  mqtt-proxy:
    container_name: mqtt-proxy
    extends:
      file: docker-compose.base.yml
      service: mqtt
    environment:
      HTTP_AUTH_HOST: ${HTTP_AUTH_HOST}
      HTTP_AUTH_PORT: 8051
      MQTT_PORT: 1884
    ports:
      - "1884:1884"

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - "5432:5432"

networks:
  backbone:
    driver: bridge