version: '2.2'

services:
  gosa:
    extends:
      file: docker-compose.base.yml
      service: gosa
    ports:
     - "8000:8000"
    
  openldap:
    extends:
      file: docker-compose.base.yml
      service: openldap
    ports:
      - "389:389"
      - "636:636"

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - "5432:5432"

  cups:
    extends:
      file: docker-compose.base.yml
      service: cups
    ports:
      - "8631:8631"

  mqtt:
    extends:
      file: docker-compose.base.yml
      service: mqtt
    ports:
      - "1883:1883"
      - "8883:8883"

networks:
  backbone:
    driver: bridge
